//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaRooms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kalingaRoom
    {
        public int id { get; set; }
        public string room_id { get; set; }
        public string blook { get; set; }
        public string floor { get; set; }
        public Nullable<int> beds { get; set; }
    }
}
