//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityAssignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mind
    {
        public int MID { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<int> track_id { get; set; }
    
        public virtual track track { get; set; }
    }
}
