//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_Details
    {
        public int id { get; set; }
        public string title { get; set; }
        public string startDateTime { get; set; }
        public string duration { get; set; }
        public string description { get; set; }
        public string location { get; set; }
        public Nullable<int> isPublic { get; set; }
        public Nullable<int> user_id { get; set; }
    }
}
